// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPcJfI_eJE0y_67jooCcOp-N1TsnsLSYY',
    appId: '1:160695091587:web:d59deed868995ae2e576b6',
    messagingSenderId: '160695091587',
    projectId: 'save-token-firebase-e1a16',
    authDomain: 'save-token-firebase-e1a16.firebaseapp.com',
    storageBucket: 'save-token-firebase-e1a16.firebasestorage.app',
    measurementId: 'G-505WXC176W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rTvEKmXPJlvTI4vxFT4T4y7CYPUIMmM',
    appId: '1:160695091587:android:cda618cd131714f8e576b6',
    messagingSenderId: '160695091587',
    projectId: 'save-token-firebase-e1a16',
    storageBucket: 'save-token-firebase-e1a16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZ4zJ8pYebOVaXF307rFnYUhH-O-CJFE',
    appId: '1:160695091587:ios:c5ef9be20875810be576b6',
    messagingSenderId: '160695091587',
    projectId: 'save-token-firebase-e1a16',
    storageBucket: 'save-token-firebase-e1a16.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYZ4zJ8pYebOVaXF307rFnYUhH-O-CJFE',
    appId: '1:160695091587:ios:c5ef9be20875810be576b6',
    messagingSenderId: '160695091587',
    projectId: 'save-token-firebase-e1a16',
    storageBucket: 'save-token-firebase-e1a16.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPcJfI_eJE0y_67jooCcOp-N1TsnsLSYY',
    appId: '1:160695091587:web:bc5c8d9fa623b6eae576b6',
    messagingSenderId: '160695091587',
    projectId: 'save-token-firebase-e1a16',
    authDomain: 'save-token-firebase-e1a16.firebaseapp.com',
    storageBucket: 'save-token-firebase-e1a16.firebasestorage.app',
    measurementId: 'G-T8QTXHGFMQ',
  );

}